name: FactionRankup
version: ${project.version}
authors: [MrMicky, Vouchs]
description: Rank up your Faction and get the strongest. With abilities for each rank.
softdepend: [Factions, Vault, PlaceholderAPI]
website: https://www.spigotmc.org/resources/factionrankup.43316/
main: fr.mrmicky.factionrankup.FactionRankup
api-version: 1.13
commands:
  frankup:
    description: Rankup your faction
    aliases: [rankup]
  factionrankup:
    description: Display information about the plugin, reload the config or change a faction level
